# Generated by Django 4.0.1 on 2022-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseimage', models.CharField(max_length=100000000)),
                ('coursetitle', models.CharField(max_length=20000)),
                ('aboutcourse', models.CharField(max_length=100000)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
